config/routes.rb
LivreRecettesV3::Application.routes.draw do

  mount Attachinary::Engine => "/attachinary"

  resources :categories
  resources :comments

  resources :recettes do
    resource :comments
  end

  match '/home' => 'recettes#home', :via => [:get]

  devise_for :users
  resources :users do
    resource :comments
  end

  root :to => 'recettes#index'
end

app/models/recette.rb
class Recette < ActiveRecord::Base
 
  validates_numericality_of :user_id, :presence => true
  validates :cuisson, :allow_blank => true, :length => {:within => 3..32}

  validates :ingredient, :presence => true
  validates :instruction, :presence => true
  validates :marinage, :allow_blank => true, :length => {:within => 3..32}

  validates :portion, :allow_blank => true, :length => {:within => 3..32}

  validates :preparation, :length => {:within => 3..32}

  validates :source, :allow_blank => true, :length => {:within => 3..1024}

  validates :titre, :length => {:within => 3..128}

  validates :vin, :allow_blank => true, :length => {:within => 3..256}

  validates :accompagnement, :allow_blank => true, :length => {:within => 3..1024}

  validates :categories, :presence => true

  has_attachment :photo, accept: [:jpg, :png, :gif], maximum: 1
  
  has_and_belongs_to_many :categories
  accepts_nested_attributes_for :categories
  
  belongs_to :users

  has_many :comments, :dependent => :destroy
  accepts_nested_attributes_for :comments, :allow_destroy => true
 
  validates_associated :comments
  def self.search(search)
    if search
      self.where(['lower(titre) LIKE ? or lower(ingredient) LIKE ?', "%#{search.downcase}%", "%#{search.downcase}%"]).order("titre")
    else
      self.order('id DESC').limit(10)
    end
  end

end

app/controllers/recettes_controller.rb
class RecettesController < ApplicationController
  before_action :do_authentication, only: %i[edit update destroy]
  before_action :signed_in?, only: [:new]

  def home
    @recettes = Recette.includes(:photo_files).search(params[:search])
    @pos = 0
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @recettes }
    end
  end

  # GET /recettes
  # GET /recettes.json
  def index
    @current_page = 'recettes'
    @recettes = Recette.includes(:photo_files).all.order('id desc').limit(15)

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @recettes }
    end
  end

  # GET /recettes/1
  # GET /recettes/1.json
  def show
    @current_page = 'recettes'

    @recette = Recette.includes(:photo_files).find(params[:id])
    @categories = Category.all

    @comments = Recette.find(params[:id]).comments.limit(3).order('id desc')
    @comment = Comment.new

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @recette }
    end
  end

  # GET /recettes/new
  # GET /recettes/new.json
  def new
    @current_page = 'recettes'
    @recette = Recette.new
    @categories = Category.all
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @recette }
    end
  end

  # GET /recettes/1/edit
  def edit
    @current_page = 'recettes'
    @recette = Recette.find(params[:id])
  end

  # POST /recettes
  # POST /recettes.json
  def create
    @current_page = 'recettes'
    @recette = Recette.new(recette_params)
    @recette.user_id = current_user[:id]
    unless params[:comment].nil?
      @comment = @recette.comments.new(content: params[:comment][:content],
                                       user_id: current_user[:id],
                                       recette_id: @recette[:id])
    end
    respond_to do |format|
      if @recette.save
        format.html { redirect_to @recette, notice: 'Recette was successfully created.' }
        format.json { render json: @recette, status: :created, location: @recette }
      else
        format.html { render action: 'new' }
        format.json { render json: @recette.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /recettes/1
  # PUT /recettes/1.json
  def update
    @current_page = 'recettes'
    @recette = Recette.find(params[:id])
    # params[:recette][:category_ids] ||= []

    @recette.update_attributes!(recette_params)
    redirect_to @recette
  end

  # DELETE /recettes/1
  # DELETE /recettes/1.json
  def destroy
    @current_page = 'recettes'
    @recette = Recette.find(params[:id])
    @recette.destroy

    respond_to do |format|
      format.html { redirect_to recettes_url }
      format.json { head :no_content }
    end
  end

  private

  # Using a private method to encapsulate the permissible parameters is just a good pattern since you'll be able to
  # reuse the same permit list between create and update. Also, you can specialize this method with per-user
  # checking of permissible attributes.
  def recette_params
    params.require(:recette).permit({ category_ids: [] },
                                    :user_id,
                                    :ingredient,
                                    :instruction,
                                    :portion,
                                    :preparation,
                                    :titre,
                                    :vin,
                                    :source,
                                    :note,
                                    :marinage,
                                    :cuisson,
                                    :accompagnement,
                                    :photo,
                                    photos_attributes: %i[signature
                                                          created_at
                                                          tags
                                                          bytes
                                                          type
                                                          url
                                                          secure_url
                                                          etag
                                                          public_id
                                                          version
                                                          width
                                                          height
                                                          format
                                                          resource_type])
  end
end

app/helpers/recettes_helper.rb
# helper module is accessible from the Recettes views
module RecettesHelper
  def fill_blanks(count)
    count -= 1 if count > 0
    the_string = ''
    while count % 4 != 0
      the_string += '<td></td>'
      break if (count % 4).zero?
      count += 1
    end
    the_string
  end

  def print_dash_if_empty(an_attribute)
    an_attribute.empty? ? '--': an_attribute
  end

end

app/views/recettes/_comments.html.erb
<%= form_for([@recette, @recette.comments.build]) do |f| %>
  <p><%= f.label :ajouter_un_commentaire %></p>
  <br>
  <p><%= f.text_area :content, :class => 'quill_container', cols: 40, rows: 20 %></p>
  <br>
  <p><%= f.submit 'Ajouter le commentaire', class: 'actions comments' %></p>
  <br>
<% end %>

app/views/recettes/_form.html.erb
<%= form_for(@recette) do |f| %>
  <% if @recette.errors.any? %>
    <section id="error_explanation">
      <h2><%= pluralize(@recette.errors.count, "error") %> prohibited this recette from being saved:</h2>

      <ul>
        <% @recette.errors.full_messages.each do |msg| %>
          <li>
            <%= msg %>
          </li>
        <% end %>
      </ul>
    </section>
  <% end %>

  <article class="recette_details">
    <section class="wide">
      <h4>Titre:</h4>
      <p><%= f.text_field :titre, :size => 48 %></p>
    </section>
    <section class="wide_no_bar">
      <h4>Photos:</h4>
      <p><%= f.attachinary_file_field :photo %></p>
    </section>
    <section class="wide_no_bar">
      <h4>Cat&eacute;gories:</h4>
      <p class="wide_no_bar">
      <ul class="categories">
        <% Category.all.each do |category| %>
          <li><%= check_box_tag "recette[category_ids][]", category.id, @recette.categories.include?(category) %> <%= category.nom %></li>
        <% end %>
      </ul>
      </p>
    </section>
    <section>
      <h4>Pr&eacuteparation:</h4>
      <p><%= f.text_field :preparation %></p>
    </section>
    <section>
      <h4>Cuisson:</h4>
      <p><%= f.text_field :cuisson %></p>
    </section>
    <section>
      <h4>Marinage:</h4>
      <p><%= f.text_field :marinage %></p>
    </section>
    <section>
      <h4>Portions:</h4>
      <p><%= f.text_field :portion %></p>
    </section>
    <section class="wide">
      <h4>Ingr&eacute;dients:</h4>
      <p><%= f.text_area :ingredient, :class => 'quill_container', :cols => 90 %></p>
    </section>
    <section class="wide">
      <h4>Instructions:</h4>
      <p><%= f.text_area :instruction, :class => 'quill_container', :cols => 90 %></p>
    </section>
    <section class="wide_no_bar">
      <h4>Notes:</h4>
      <p><%= f.text_area :note, :class => 'quill_container', :cols => 90 %></p>
    </section>
    <section class="wide_no_bar">
      <h4>Accompagnement:</h4>
      <p><%= f.text_area :accompagnement, :class => 'quill_container', :cols => 40, :rows => 5 %></p>
    </section>
    <section class="wide_no_bar">
      <h4>Vin:</h4>
      <p><%= f.text_area :vin, :class => 'quill_container', :cols => 40, :rows => 5 %></p>
    </section>
    <section class="wide_no_bar">
      <h4>Source:</h4>
      <p><%= f.text_field :source, :size => 48 %></p>
    </section>
    <section>
      <p><%= f.submit 'Soumettre', class: 'actions' %></p>
    </section>
  </article>
<% end %>

app/views/recettes/_results.html.erb
<div class="recettes_list">
	<% @recettes.each do |recette| %>
		<div class="recette">
			<p>
				<% if recette.photo %>
					<%= link_to(cl_image_tag(recette.photo.path, :transformation => {:width => 275, :height => 275, :crop => "fit"}), recette, target: '_blank') %>
				<% else %>
					<i class="fas fa-utensils fa-5x"></i>
				<% end %>
			</p>
			<p><%= link_to(recette.titre, recette, target: '_blank') %></p>
			<p><%= link_to get_username(recette[:user_id]), user_path(recette[:user_id]), class: 'user' %></p>
		</div>
	<% end %>
</div>

app/views/recettes/edit.html.erb
<main class="contenu">
	<h3>Modification d'une recette</h3>
	<header class="header">
		<%= link_to 'Voir', @recette, class:'actions' %> |
		<%= link_to 'Retour', recettes_path, class: 'actions' %>
	</header>
	<%= render 'form' %>

</main>

app/views/recettes/home.html.erb
<main class='contenu'>
  <% if current_user %>
      <h3><%= "Bienvenue #{get_username(current_user.id)} sur Nos Recettes" %></h3>
  <% end %>

  <%= render 'results' %>
</main>

app/views/recettes/index.html.erb
<main class="contenu">
  <h3>15 Derni&egrave;res recettes</h3>
  <article class="recettes_list">
    <% @recettes.each do |recette| %>
      <section class="recette">
        <p>
          <% if recette.photo %>
            <%= link_to(cl_image_tag(recette.photo.path, :transformation => {:width => 275, :height => 275, :crop => "fit"}), recette, target: '_blank') %>
          <% else %>
            <i class="fas fa-utensils fa-5x icon-padding"></i>
          <% end %>
        </p>
        <p><%= link_to(recette.titre, recette, target: '_blank') %></p>
        <p><%= link_to get_username(recette[:user_id]), user_path(recette[:user_id]), class: 'user' %></p>
      </section>
    <% end %>
  </article>
</main>

app/views/recettes/new.html.erb
<main class="contenu">
	<h3>Nouvelle recette</h3>
<div align="center" class="actions">
	<%= link_to 'Retour', recettes_path %>
</div>
	<%= render 'form' %>
</div>

app/views/recettes/show.html.erb
<main class="contenu">
  <h3> <%= @recette.titre %> </h3>
  <p id="notice">
    <%= flash[:notice] %>
  </p>
  <p id="error">
    <%= flash[:error] %>
  </p>
  <header class="header">
    <% if do_authentication then %>
      <%= link_to 'Modifier', edit_recette_path(@recette),  class: 'actions' %> |
    <% end %>
    <%= link_to 'Retour', recettes_path, class: 'actions' %>
    <% if do_authentication then %> |
      <%= link_to 'Effacer', @recette, confirm: 'Etes-Vous Certain?', method: :delete, class: 'actions' %>
    <% end %>
  </header>
  <article class="recette_details">
    <% if @recette.photo then %>
      <%= link_to(cl_image_tag(@recette.photo.path, {size: '125x125', crop: :fit}), "http://res.cloudinary.com/livre-recettes/image/upload/#{@recette.photo.path}", target: :blank) %>
    <% else %>
      <i class="fas fa-utensils fa-5x icon"></i>
    <% end %>
    <section>
      <h4>Cat&eacute;gories:</h4>
      <ul>
        <% @recette.categories.each do |categorie| %>
          <li><%= categorie.nom %></li>
        <% end %>
      </ul>
    </section>
    <section>
      <h4>Pr&eacute;paration:</h4>
      <p><%= print_dash_if_empty(@recette.preparation) %></p>
    </section>
    <section>
      <h4>Cuisson:</h4>
      <p><%= print_dash_if_empty(@recette.cuisson) %></p>
    </section>
    <section>
      <h4>Marinage:</h4>
      <p><%= print_dash_if_empty(@recette.marinage) %></p>
    </section>
    <section>
      <h4>Portions:</h4>
      <p><%= print_dash_if_empty(@recette.portion) %></p>
    </section>
    <section class="wide">
      <h4>Ingr&eacute;dients:</h4>
      <p><%= @recette.ingredient.html_safe %></p>
    </section>
    <section class="wide">
      <h4>Instructions:</h4>
      <p><%= @recette.instruction.html_safe %></p>
    </section>
    <section>
      <h4>Note:</h4>
      <p><%= @recette.note.html_safe %></p>
    </section>
    <section>
      <h4>Accompagnement:</h4>
      <p><%= @recette.accompagnement.html_safe %></p>
    </section>
    <section>
      <h4>Vin:</h4>
      <p><%= @recette.vin.html_safe %></p>
    </section>
    <section class="wide">
      <h4>Source:</h4>
      <p><%= check_if_link(@recette.source.html_safe) ? link_to(@recette.source, @recette.source, target: '_blank') : @recette.source.html_safe %></p>
    </section>
    <section>
      <h4>Auteur:</h4>
      <p><%= link_to get_username(@recette[:user_id]), user_path(@recette[:user_id]) %></p>
    </section>
    <section class="wide">
      <% if current_user then %>
        <%= render 'comments' %>
      <% end %>
      <% if @comments != [] then %>
        <h4>Derniers commentaires:</h4>
        <p><%= link_to 'Voir tous les commentaires', recette_comments_path(@recette) %></p>

        <% @comments.each do |comment| %>
          <h5><%= get_username(comment[:user_id]) %></h5>
          <p><%= comment[:content].html_safe %></p>
          <p class="comment">
            <% if do_authentication_comments(comment[:id]) %>
              <%= link_to 'Effacer', comment, method: :delete, notice: 'Commentaire effacer', class: 'actions' %>
              | <%= link_to('Modifier', edit_comment_path(comment), class: 'actions') %>
            <% end %>
          </p>
        <% end %>
      <% end %>
    </section>
  </article>
</main>