config/routes.rb
LivreRecettesV3::Application.routes.draw do

  mount Attachinary::Engine => "/attachinary"

  resources :categories
  resources :comments

  resources :recettes do
    resource :comments
  end

  match '/home' => 'recettes#home', :via => [:get]

  devise_for :users
  resources :users do
    resource :comments
  end

  root :to => 'recettes#index'
end

app/views/shared/_footer.html.erb
<footer class="debug">
  <%=
    debug(params) if Rails.env.development?
  %>
</footer>
</div>

app/views/shared/_header.html.erb
<header id="top_header">
  <a href="<%= home_path %>" class="site_name"><h1><span class="nos">Nos </span><br></br>Recettes</h1></a>
</header>
<%= render 'shared/search' %>
<navigation>
  <div class="nav_background">
    <nav class="nav_container">
      <ul>
        <% if current_user then %>
          <li><%= link_to 'Nouvelle Recette', new_recette_path %></li>
        <% end %>
        <% if user_is_admin? then %>
          <li><%= link_to 'Nouvelle Categorie', new_category_path %></li>
        <% end %>
        <li><%= link_to 'Recettes', recettes_path, :class => current_page?("recettes") %></li>
        <li><%= link_to 'Categories', categories_path, :class => current_page?("categories") %></li>
        <li><a href="mailto:info (at) nosrecettes (dot) ca">Contact</a></li>
        <% if !current_user then %>
          <li><%= link_to 'Connexion', new_user_session_path, :class => current_page?("connexion") %></li>
        <% else %>
          <li><%= link_to 'Deconnexion', destroy_user_session_path, :method => :delete %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</navigation>

app/views/shared/_search.html.erb
<header id="search_section">
  <div class="search_form">
    <%= form_tag home_path, :method => 'get', :id => 'search_form' do %>
      <%= text_field_tag :search, params[:search], :size => 28 %>
      <%= submit_tag 'Rechercher', :id => "soumettre" %>
    <% end %>
  </div>
</header>