config/routes.rb
LivreRecettesV3::Application.routes.draw do

  mount Attachinary::Engine => "/attachinary"

  resources :categories
  resources :comments

  resources :recettes do
    resource :comments
  end

  match '/home' => 'recettes#home', :via => [:get]

  devise_for :users
  resources :users do
    resource :comments
  end

  root :to => 'recettes#index'
end

app/models/category.rb
class Category < ActiveRecord::Base
  
  validates :nom, :length => {:within => 3..256}, :uniqueness => true
  has_and_belongs_to_many :recettes
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController

  before_action :do_authentication_admin, :except => [:show, :index]
  # GET /categories
  # GET /categories.json
  def index

    @current_page = "categories"
    @pos = 0
    @categories = Category.all.order("nom")

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @categories }
    end
  end

  # GET /categories/1
  # GET /categories/1.json
  def show
    @current_page = "categories"
    @pos = 0
    @category = Category.find(params[:id])

    recettes_pour_category(@category[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @category }
    end
  end

  # GET /categories/new
  # GET /categories/new.json
  def new
    @current_page = "categories"

    @category = Category.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @category }
    end
  end

  # GET /categories/1/edit
  def edit
    @current_page = "categories"
    @category = Category.find(params[:id])
  end

  # POST /categories
  # POST /categories.json
  def create
    @current_page = "categories"
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to @category, notice: 'Categorie was successfully created.' }
        format.json { render json: @category, status: :created, location: @category }
      else
        format.html { render action: "new" }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /categories/1
  # PUT /categories/1.json
  def update
    @current_page = "categories"
    @category = Category.find(params[:id])

    @category.update_attributes!(category_params)
    redirect_to category_path(@category)
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    @current_page = "categories"
    @category = Category.find(params[:id])
    @category.destroy

    respond_to do |format|
      format.html { redirect_to categories_url }
      format.json { head :no_content }
    end
  end

  ### start of private block
  private

  def recettes_pour_category(une_categorie)
    @recettes = Category.find(une_categorie).recettes.order("titre asc")
  end

  # Using a private method to encapsulate the permissible parameters is just a good pattern
  # since you'll be able to reuse the same permit list between create and update. Also, you
  # can specialize this method with per-user checking of permissible attributes.
  def category_params
    params.require(:category).permit(:nom)
  end

end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/_form.html.erb
<%= form_for(@category) do |f| %>
<% if @category.errors.any? %>
<div id="error_explanation">
	<h2><%= pluralize(@category.errors.count, 'error') %> prohibited this category from being saved:</h2>

	<ul>
		<% @category.errors.full_messages.each do |msg| %>
		<li><%= msg %></li>
		<% end %>
	</ul>
</div>
<% end %>
<section>
	<h4>Nom:</h4>
	<%= f.text_field :nom %>
	<%= f.submit 'Soumettre', class: 'actions' %>
</section>
<% end %>

app/views/categories/edit.html.erb
<main class="contenu">
	<h3>Modification d'une cat&eacute;gorie</h3>
	<p id="notice">
		<%= notice %>
	</p>
	<table width="100%%">
		<tr align="center">
			<td><%= link_to 'Voir', @category %> | <%= link_to 'Retour', categories_path %></td>
		</tr>
		<tr>
			<td><%= render 'form' %></td>
		</tr>
	</table>
</main>

app/views/categories/index.html.erb
<main class="contenu">
  <header>
    <h3>Liste des cat&eacute;gories</h3>
  </header>
  <section class="categories_header">
    <h4>Nom</h4>
    <hr>
  </section>
  <section>
    <% @categories.each do |category| %>
      <section class="categories_recettes_list">
        <%= link_to category.nom, category %>
        <%= pluralize(nombre_recette_pour_category(category), "recette") %>
        <% if user_is_admin? then %>
          <%= link_to 'Modifier', edit_category_path(category), class: 'categories_actions' %>
        <% end %>
        <% if user_is_admin? then %>
          <%= link_to 'Effacer', category, method: :delete, data: {confirm: 'Etes-vous certain?'}, class: 'categories_actions' %>
        <% end %>
      </section>
    <% end %>

  </section>
</main>

app/views/categories/new.html.erb
<main class="contenu">
	<h3>Nouvelle cat&eacute;gorie</h3>
	<p id="notice">
		<%= notice %>
	</p>
	<table width="100%%">
		<tr align="center">
			<td><%= link_to 'Retour', categories_path %></td>
		</tr>
		<tr>
			<td><%= render 'form' %></td>
		</tr>
	</table>
</main>

app/views/categories/show.html.erb
<main class="contenu">
  <h3><%= @category.nom %></h3>

  <p id="notice">
    <%= notice %>
  </p>
  <header class="header">
    <% if user_is_admin? then %>
      <%= link_to 'Modifier', edit_category_path(@category), class: 'actions' %> |
    <% end %>
    <%= link_to 'Retour', categories_path, class: 'actions' %>
  </header>
  <section class="recettes_list">
    <% @recettes.each do |recette| %>
      <div class="recette">
        <p>
          <% if recette.photo %>
            <%= link_to(cl_image_tag(recette.photo.path, :transformation => {:width => 275, :height => 275, :crop => "fit"}), recette, target: '_blank') %>
          <% else %>
            <i class="fas fa-utensils fa-5x"></i>
          <% end %>
        </p>
        <p><%= link_to(recette.titre, recette, target: '_blank') %></p>
        <p><%= link_to get_username(recette[:user_id]), user_path(recette[:user_id]), class: 'user' %></p>
      </div>
    <% end %>
  </section>
</main>